//
// Created by lin on 2026/6/2.
//

#ifndef CI_SOURCE_FINISHED_DSP_TEST_COMMUNICATION_H
#define CI_SOURCE_FINISHED_DSP_TEST_COMMUNICATION_H
void Global_OUTPUT(void);
#endif //CI_SOURCE_FINISHED_DSP_TEST_COMMUNICATION_H